version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pa55word

  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080